version: "3.9"

services:
  docs-builder:
    build: ./dockerfiles/app
    container_name: docs-builder
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8500:8500"
      - "9000:9000"
    volumes:
      - ./:/cshd
    working_dir: /cshd/app
    entrypoint: bash PID_1.sh
    #TODO: need to run as non-root at some point

