version: "3.9"

services:
  docs-builder-cicd:
    build: ../dockerfiles/app
    container_name: docs-builder-cicd
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOW_HOSTS=${ALLOW_HOSTS}
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ../:/dcsp
    working_dir: /dcsp/app
    entrypoint: bash PID_1_cicd.sh

