name: cicd
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./dockerfiles/app/
          file: ./dockerfiles/app/Dockerfile
          push: true
          tags: cotswoldsmaker/dcsp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Run linter, security, typing and unit testing in Docker container
        run: >
          DJANGO_SECRET_KEY='${{ secrets.DJANGO_SECRET_KEY }}' 
          ALLOW_HOSTS='${{ secrets.ALLOW_HOSTS }}' 
          docker-compose -f .cicd/docker-compose.yml up --exit-code-from docs-builder-cicd