name: cicd
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Testing inside Docker container
        run: >
          DJANGO_SECRET_KEY='${{ secrets.DJANGO_SECRET_KEY }}' 
          ALLOW_HOSTS='${{ secrets.ALLOW_HOSTS }}' 
          docker-compose -f .cicd/docker-compose.yml up --exit-code-from docs-builder-cicd

          
      
      