name: cicd
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run linter, security, typing and unit testing in Docker container
        run: >
          DJANGO_SECRET_KEY='${{ secrets.DJANGO_SECRET_KEY }}' 
          ALLOW_HOSTS='${{ secrets.ALLOW_HOSTS }}' 
          docker-compose -f .cicd/docker-compose.yml up --exit-code-from docs-builder-cicd