site_name: Clinical Safety Hazard Documentation 

plugins:
  - macros

theme:
  name: material
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  custom_dir: overrides

extra:
  generator: false

dev_addr: 0.0.0.0:9000

INHERIT: ./docs/placeholders.yml
